import * as THREE from 'three';
import './styles.css';

const canvas = document.querySelector('#game');
const $ = (id) => document.getElementById(id);
const ui = { hole: $('hole'), par: $('par'), strokes: $('strokes'), score: $('score'), wind: $('wind'), windArrow: $('windArrow'), lie: $('lie'), distance: $('distance'), meter: $('meterFill'), shotTitle: $('shotTitle'), shotHint: $('shotHint'), hint: $('aimHint'), finish: $('finish'), finishTitle: $('finishTitle'), finishText: $('finishText'), finishStrokes: $('finishStrokes'), loading: $('loading') };

const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.outputColorSpace = THREE.SRGBColorSpace; renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.05;
const scene = new THREE.Scene(); scene.background = new THREE.Color(0x9db6bc); scene.fog = new THREE.FogExp2(0x9db6bc, .018);
const camera = new THREE.PerspectiveCamera(48, innerWidth / innerHeight, .1, 220);
const hemi = new THREE.HemisphereLight(0xe8f5ff, 0x173d27, 2.0); scene.add(hemi);
const sun = new THREE.DirectionalLight(0xfff4d6, 3.2); sun.position.set(-18, 26, 12); sun.castShadow = true; sun.shadow.mapSize.set(2048, 2048); sun.shadow.camera.left = -32; sun.shadow.camera.right = 32; sun.shadow.camera.top = 32; sun.shadow.camera.bottom = -32; scene.add(sun, sun.target);

const world = new THREE.Group(); scene.add(world);
const ballRadius = .22;
let course, ball, cup, flag, aimLine, guideDots, strokeCount = 0, totalScore = 0, holeIndex = 0, rolling = false, aiming = false, dragStart = null, cameraMode = 0, soundOn = true, lastT = performance.now();
const velocity = new THREE.Vector3(); const tee = new THREE.Vector3(); const wind = new THREE.Vector2(); const desiredCamera = new THREE.Vector3(); const cameraLook = new THREE.Vector3();
const raycaster = new THREE.Raycaster(); const pointer = new THREE.Vector2(); const groundPlane = new THREE.Plane(new THREE.Vector3(0,1,0), 0);
const surfaces = []; const obstacles = []; const hazards = []; const courseMeshes = [];

const courses = [
  { name:'The First Cut', par:3, wind:5, width:14, length:27, tee:[-3.8,10], cup:[2.7,-11], sand:[[-2,-2,4.5,3.2]], water:[[5.1,-5.5,2.7,5]], rocks:[[-4.8,-6.5,1.2,3.2]], slopes:[{x:1,z:-7,r:8,sx:-.03,sz:.01}] },
  { name:'Creekside', par:4, wind:9, width:17, length:34, tee:[3.5,13], cup:[-3.4,-14], sand:[[3,-3,3.8,5],[-4,-9,3.4,2.6]], water:[[0,2,12,3.7]], rocks:[[5,-10,2,5],[-6,-4,1.2,4]], slopes:[{x:-2,z:-9,r:10,sx:.025,sz:-.02}] },
  { name:'Pine Break', par:3, wind:7, width:15, length:30, tee:[-4,12], cup:[4,-12], sand:[[0,-6,4.4,3]], water:[[-4,0,3,5]], rocks:[[0,3,5,.8],[3,-3,.9,5]], slopes:[{x:3,z:-7,r:8,sx:-.035,sz:.01}] }
];

function material(color, roughness=.8, metalness=0) { return new THREE.MeshStandardMaterial({color,roughness,metalness}); }
const mats = { fair:material(0x4c9c58,.95), fringe:material(0x397a45,.98), rough:material(0x255a35,1), sand:material(0xd8c48b,1), water:new THREE.MeshPhysicalMaterial({color:0x2b93a8,roughness:.14,metalness:.08,transparent:true,opacity:.78,clearcoat:.8}), rock:material(0x6a7165,.95), cup:material(0x101411,.5), pole:material(0xf6f2df,.45), flag:material(0xd95745,.7), white:material(0xf8f7ef,.4), wood:material(0x6d5130,1), leaf:material(0x25583a,1) };

function addMesh(mesh, target=world) { mesh.castShadow = true; mesh.receiveShadow = true; target.add(mesh); courseMeshes.push(mesh); return mesh; }
function clearCourse() { courseMeshes.forEach(m=>m.parent?.remove(m)); courseMeshes.length=0; surfaces.length=0; obstacles.length=0; hazards.length=0; if (ball) world.remove(ball); if (aimLine) world.remove(aimLine); if (guideDots) world.remove(guideDots); }
function roundedRectShape(w,l,r=.9){ const s=new THREE.Shape(), x=-w/2,z=-l/2; s.moveTo(x+r,z); s.lineTo(x+w-r,z); s.quadraticCurveTo(x+w,z,x+w,z+r); s.lineTo(x+w,z+l-r); s.quadraticCurveTo(x+w,z+l,x+w-r,z+l); s.lineTo(x+r,z+l); s.quadraticCurveTo(x,z+l,x,z+l-r); s.lineTo(x,z+r); s.quadraticCurveTo(x,z,x+r,z); return s; }
function patch(w,l,mat,y=0){ const g=new THREE.ShapeGeometry(roundedRectShape(w,l)); g.rotateX(-Math.PI/2); const m=addMesh(new THREE.Mesh(g,mat));m.position.y=y;return m; }
function heightAt(x,z){ let h=0; for(const s of course.slopes){const dx=x-s.x,dz=z-s.z,d=Math.hypot(dx,dz);if(d<s.r){const q=1-d/s.r;h+=q*q*(s.sx*dx+ s.sz*dz)*6;}} return h; }
function surfaceAt(x,z){ for(const h of hazards) if(x>h.x-h.w/2&&x<h.x+h.w/2&&z>h.z-h.l/2&&z<h.z+h.l/2) return 'water'; for(const s of surfaces) if(x>s.x-s.w/2&&x<s.x+s.w/2&&z>s.z-s.l/2&&z<s.z+s.l/2) return s.type; return 'rough'; }
function makeTree(x,z,scale=1){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.12*scale,.17*scale,1.2*scale,8),mats.wood);trunk.position.y=.6*scale;const crown=new THREE.Mesh(new THREE.ConeGeometry(.78*scale,2.6*scale,10),mats.leaf);crown.position.y=2*scale;g.add(trunk,crown);g.position.set(x,heightAt(x,z),z);g.traverse(n=>{if(n.isMesh){n.castShadow=n.receiveShadow=true}});world.add(g);courseMeshes.push(g)}
function makeRock(x,z,w,l){const m=addMesh(new THREE.Mesh(new THREE.DodecahedronGeometry(.55,0),mats.rock));m.scale.set(w,1,l);m.position.set(x,.38,z);obstacles.push({x,z,w:w*.55,l:l*.55,mesh:m});}
function buildCourse(){ clearCourse(); course=courses[holeIndex%courses.length]; wind.set((Math.random()-.5)*course.wind*.11,(Math.random()-.5)*course.wind*.11); ui.hole.textContent=String(holeIndex+1).padStart(2,'0');ui.par.textContent=course.par;ui.wind.textContent=`${course.wind} mph`;ui.windArrow.style.transform=`rotate(${Math.atan2(wind.x,-wind.y)}rad)`;ui.strokes.textContent='0';strokeCount=0;
  patch(70,70,mats.rough,-.08); const fair=patch(course.width,course.length,mats.fringe,.004);fair.position.z=-1; surfaces.push({x:0,z:-1,w:course.width,l:course.length,type:'fringe'}); const green=patch(8,8,mats.fair,.02);green.position.set(course.cup[0],.01,course.cup[1]);surfaces.push({x:course.cup[0],z:course.cup[1],w:8,l:8,type:'green'});
  for(const [x,z,w,l] of course.sand){const m=patch(w,l,mats.sand,.028);m.position.set(x,.028,z);surfaces.push({x,z,w,l,type:'sand'});} for(const [x,z,w,l] of course.water){const m=patch(w,l,mats.water,.025);m.position.set(x,.025,z);hazards.push({x,z,w,l});}
  for(const r of course.rocks)makeRock(...r); for(let i=0;i<19;i++){const side=i%2?1:-1;const x=side*(course.width/2+2+Math.random()*7);const z=-course.length/2+Math.random()*course.length;makeTree(x,z,.65+Math.random()*.65)}
  const cupGroup=new THREE.Group();const holeMesh=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.06,32),mats.cup);holeMesh.position.y=.02;cupGroup.add(holeMesh);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.022,.022,3,10),mats.pole);pole.position.y=1.5;cupGroup.add(pole);const flg=new THREE.Mesh(new THREE.PlaneGeometry(1.05,.62),mats.flag);flg.position.set(.53,2.55,0);flg.rotation.y=Math.PI/2;cupGroup.add(flg);cupGroup.position.set(course.cup[0],heightAt(...course.cup)+.02,course.cup[1]);world.add(cupGroup);courseMeshes.push(cupGroup);cup=cupGroup;
  const ballGeo=new THREE.SphereGeometry(ballRadius,32,20);ball=new THREE.Mesh(ballGeo,mats.white);tee.set(course.tee[0],heightAt(...course.tee)+ballRadius,course.tee[1]);ball.position.copy(tee);ball.castShadow=true;world.add(ball);
  aimLine=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xf5f1d8,transparent:true,opacity:.7}));guideDots=new THREE.Group();world.add(aimLine,guideDots);aimLine.visible=false;guideDots.visible=false; updateUI(); centerCamera(true);
}
function normalAt(x,z){const e=.12;const hx=heightAt(x+e,z)-heightAt(x-e,z),hz=heightAt(x,z+e)-heightAt(x,z-e);return new THREE.Vector3(-hx/(2*e),1,-hz/(2*e)).normalize();}
function updateUI(){const d=Math.hypot(cup.position.x-ball.position.x,cup.position.z-ball.position.z);ui.distance.textContent=`${(d*1.094).toFixed(1)} yd`;const type=surfaceAt(ball.position.x,ball.position.z);ui.lie.textContent=type.toUpperCase();ui.shotTitle.textContent=rolling?'Watch the roll': type==='sand'?'Escape the bunker':d<5?'Read the green':'Pick your line';ui.shotHint.textContent=rolling?'Wind and slope are in play.':'Drag back from the ball, then release to putt.';ui.score.textContent=totalScore===0?'E':totalScore>0?`+${totalScore}`:`${totalScore}`;}
function showAim(point){const dx=ball.position.x-point.x,dz=ball.position.z-point.z,len=Math.min(12,Math.hypot(dx,dz)*1.25);if(len<.1)return;const nx=dx/Math.hypot(dx,dz),nz=dz/Math.hypot(dx,dz);const pts=[];for(let i=0;i<=24;i++){const t=i/24;pts.push(new THREE.Vector3(ball.position.x+nx*len*t,heightAt(ball.position.x+nx*len*t,ball.position.z+nz*len*t)+.1,ball.position.z+nz*len*t));}aimLine.geometry.setFromPoints(pts);aimLine.visible=true;guideDots.visible=false;ui.meter.style.width=`${Math.min(100,len/12*100)}%`;}
function hideAim(){aimLine.visible=false;guideDots.visible=false;ui.meter.style.width='0%';ui.hint.style.display='none';}
function shoot(point){const dx=ball.position.x-point.x,dz=ball.position.z-point.z,dist=Math.hypot(dx,dz);if(dist<.12)return;const force=Math.min(14,dist*1.32);velocity.set(dx/dist*force,0,dz/dist*force);strokeCount++;ui.strokes.textContent=strokeCount;rolling=true;hideAim();playTone(125,0.07,'triangle',.16);updateUI();}
function resetBall(){if(rolling)return;ball.position.copy(tee);velocity.set(0,0,0);hideAim();updateUI();}
function finishHole(){rolling=false;const diff=strokeCount-course.par;totalScore+=diff;const label=diff<=-2?'Eagle!':diff===-1?'Birdie!':diff===0?'Par!':diff===1?'Bogey':'Keep practicing';ui.finishTitle.textContent=label;ui.finishText.textContent=`${course.name} — par ${course.par}.`;ui.finishStrokes.textContent=strokeCount;ui.finish.classList.add('on');playTone(440,.12,'sine',.13);setTimeout(()=>playTone(660,.2,'sine',.12),110);}
function physics(dt){if(!rolling)return;const type=surfaceAt(ball.position.x,ball.position.z);if(type==='water'){playTone(90,.16,'sine',.16);rolling=false;setTimeout(resetBall,360);return;}const n=normalAt(ball.position.x,ball.position.z);velocity.x+=(-n.y*n.x*9.81+wind.x*.055)*dt;velocity.z+=(-n.y*n.z*9.81+wind.y*.055)*dt;const friction=type==='sand'?2.9:type==='rough'?1.1:type==='green'?.34:.58;const speed=Math.hypot(velocity.x,velocity.z);if(speed){const next=Math.max(0,speed-friction*dt);velocity.x*=next/speed;velocity.z*=next/speed;}ball.position.x+=velocity.x*dt;ball.position.z+=velocity.z*dt;ball.position.y=heightAt(ball.position.x,ball.position.z)+ballRadius;for(const o of obstacles){const dx=ball.position.x-o.x,dz=ball.position.z-o.z;if(Math.abs(dx)<o.w+ballRadius&&Math.abs(dz)<o.l+ballRadius){if(Math.abs(dx/o.w)>Math.abs(dz/o.l)){ball.position.x=o.x+Math.sign(dx)*(o.w+ballRadius);velocity.x*=-.58}else{ball.position.z=o.z+Math.sign(dz)*(o.l+ballRadius);velocity.z*=-.58}playTone(195,.035,'square',.06)}}ball.rotation.z-=velocity.x*dt/ballRadius;ball.rotation.x+=velocity.z*dt/ballRadius;const toCup=new THREE.Vector2(cup.position.x-ball.position.x,cup.position.z-ball.position.z),cd=toCup.length();if(cd<.78&&type==='green'){const pull=(.78-cd)*9;velocity.x+=toCup.x/cd*pull*dt;velocity.z+=toCup.y/cd*pull*dt;}if(cd<.30&&speed<2.0){ball.position.y-=dt*1.4;if(ball.position.y<heightAt(ball.position.x,ball.position.z)-.32){finishHole();return;}}if(Math.hypot(velocity.x,velocity.z)<.035){velocity.set(0,0,0);rolling=false;updateUI();}}
function centerCamera(immediate=false){const target=cameraMode===0?new THREE.Vector3(ball.position.x-7,7.2,ball.position.z+9):new THREE.Vector3(ball.position.x,14,ball.position.z+13);if(immediate)camera.position.copy(target);cameraLook.set(ball.position.x+(cup.position.x-ball.position.x)*.22,0,ball.position.z+(cup.position.z-ball.position.z)*.22);camera.lookAt(cameraLook)}
function updateCamera(dt){const target=cameraMode===0?desiredCamera.set(ball.position.x-7,7.2,ball.position.z+9):desiredCamera.set(ball.position.x,14,ball.position.z+13);camera.position.lerp(target,1-Math.exp(-3*dt));cameraLook.lerp(new THREE.Vector3(ball.position.x+(cup.position.x-ball.position.x)*.22,.1,ball.position.z+(cup.position.z-ball.position.z)*.22),1-Math.exp(-4*dt));camera.lookAt(cameraLook)}
let audioCtx;function playTone(freq,duration,type,volume){if(!soundOn)return;audioCtx??=new AudioContext();if(audioCtx.state==='suspended')audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(volume,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);osc.connect(gain).connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration)}
function eventPoint(e){const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;raycaster.setFromCamera(pointer,camera);const hit=new THREE.Vector3();return raycaster.ray.intersectPlane(groundPlane,hit)?hit:null}
canvas.addEventListener('pointerdown',e=>{if(rolling)return;audioCtx??=new AudioContext();dragStart=eventPoint(e);if(dragStart){aiming=true;canvas.setPointerCapture(e.pointerId);ui.hint.style.display='block';ui.hint.style.left=`${e.clientX+12}px`;ui.hint.style.top=`${e.clientY-24}px`;}});canvas.addEventListener('pointermove',e=>{if(!aiming)return;const p=eventPoint(e);if(p)showAim(p)});canvas.addEventListener('pointerup',e=>{if(!aiming)return;const p=eventPoint(e);aiming=false;if(p)shoot(p);else hideAim()});
$('reset').onclick=resetBall;$('view').onclick=()=>{cameraMode=(cameraMode+1)%2;$('view').innerHTML=cameraMode?'◌ <span>Follow</span>':'◉ <span>View</span>'};$('sound').onclick=()=>{soundOn=!soundOn;$('sound').innerHTML=soundOn?'♬ <span>Sound</span>':'× <span>Muted</span>'};$('next').onclick=()=>{ui.finish.classList.remove('on');holeIndex++;buildCourse()};
addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')resetBall();if(e.key.toLowerCase()==='v')$('view').click();if(e.key.toLowerCase()==='m')$('sound').click()});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function loop(t){const dt=Math.min(.035,(t-lastT)/1000);lastT=t;physics(dt);updateCamera(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}
buildCourse();setTimeout(()=>ui.loading.classList.add('off'),500);requestAnimationFrame(loop);
